# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  release:
    branches: [ 1.17 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: GH Release
    # You may pin to the exact commit or the version.
    # uses: softprops/action-gh-release@b7e450da2a4b4cb4bfbae528f788167786cfcedf
      uses: softprops/action-gh-release@v0.1.5
      with:
        # Note-worthy description of changes in release
        body: this is a beta build and a change log cannot be provided # optional
        # Path to load note-worthy description of changes in release from
        body_path: This is automatically made for a release # optional
        # Gives the release a custom name. Defaults to tag name
        name: Auto-CI Release # optional
        # Creates a draft release. Defaults to false
        draft: false # optional
        # Identify the release as a prerelease. Defaults to false
        prerelease: true # optional
        # Newline-delimited list of path globs for asset files to upload
        files: bulit/libs/*.jar # optional
